# Usar uma imagem oficial do Node.js como base
FROM node:18-alpine

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos package.json e yarn.lock primeiro
COPY package.json yarn.lock ./

# Instalar as dependências
RUN yarn install --frozen-lockfile

# Copiar o restante do código
COPY . .

# Gerar o Prisma Client
RUN yarn prisma generate

# Compilar o projeto
RUN yarn build

# Expor a porta que a aplicação irá rodar
EXPOSE 3000

# Definir o comando padrão para iniciar o app
CMD ["yarn", "start:prod"]